/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;



import static calculadora.JVistaPrincipal.ayuda;
import static calculadora.JVistaPrincipal.datos;
import static calculadora.JVistaPrincipal.fav;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.util.GregorianCalendar;

public class JCalculadora extends javax.swing.JFrame {
    
    public double pnumero;
    public double snumero;
    public double otron;
    public String operacion;
    JTemp temp= new JTemp();
    /**
     * Creates new form JCalculadora
     */
    public JCalculadora() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Calculadora");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BNocho = new javax.swing.JButton();
        Bsuma = new javax.swing.JButton();
        Braizn = new javax.swing.JButton();
        Bresta = new javax.swing.JButton();
        Bmultiplicacion = new javax.swing.JButton();
        Bmen = new javax.swing.JButton();
        panel = new javax.swing.JLabel();
        Bdivision = new javax.swing.JButton();
        Belevacion = new javax.swing.JButton();
        Braiz = new javax.swing.JButton();
        BNuno = new javax.swing.JButton();
        BNtres = new javax.swing.JButton();
        Bdos = new javax.swing.JButton();
        BNseis = new javax.swing.JButton();
        BNcinco = new javax.swing.JButton();
        BNcuatro = new javax.swing.JButton();
        BNnueve = new javax.swing.JButton();
        BNcero = new javax.swing.JButton();
        Binverso = new javax.swing.JButton();
        BNsiete = new javax.swing.JButton();
        Bfactorial = new javax.swing.JButton();
        Bigual = new javax.swing.JButton();
        Bclear = new javax.swing.JButton();
        Bsave = new javax.swing.JButton();
        panel1 = new javax.swing.JLabel();
        imaginario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        BNocho.setText("8");
        BNocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNochoActionPerformed(evt);
            }
        });

        Bsuma.setText("+");
        Bsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsumaActionPerformed(evt);
            }
        });

        Braizn.setText("rn");
        Braizn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BraiznActionPerformed(evt);
            }
        });

        Bresta.setText("-");
        Bresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrestaActionPerformed(evt);
            }
        });

        Bmultiplicacion.setText("x");
        Bmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmultiplicacionActionPerformed(evt);
            }
        });

        Bmen.setText("(-)");
        Bmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmenActionPerformed(evt);
            }
        });

        panel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panel.setToolTipText("");
        panel.setOpaque(true);

        Bdivision.setText("/");
        Bdivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdivisionActionPerformed(evt);
            }
        });

        Belevacion.setText("^");
        Belevacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BelevacionActionPerformed(evt);
            }
        });

        Braiz.setText("r");
        Braiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BraizActionPerformed(evt);
            }
        });

        BNuno.setText("1");
        BNuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNunoActionPerformed(evt);
            }
        });

        BNtres.setText("3");
        BNtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNtresActionPerformed(evt);
            }
        });

        Bdos.setText("2");
        Bdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdosActionPerformed(evt);
            }
        });

        BNseis.setText("6");
        BNseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNseisActionPerformed(evt);
            }
        });

        BNcinco.setText("5");
        BNcinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNcincoActionPerformed(evt);
            }
        });

        BNcuatro.setText("4");
        BNcuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNcuatroActionPerformed(evt);
            }
        });

        BNnueve.setText("9");
        BNnueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNnueveActionPerformed(evt);
            }
        });

        BNcero.setText("0");
        BNcero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNceroActionPerformed(evt);
            }
        });

        Binverso.setText("1/x");
        Binverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinversoActionPerformed(evt);
            }
        });

        BNsiete.setText("7");
        BNsiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNsieteActionPerformed(evt);
            }
        });

        Bfactorial.setText("!");
        Bfactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfactorialActionPerformed(evt);
            }
        });

        Bigual.setText("=");
        Bigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BigualActionPerformed(evt);
            }
        });

        Bclear.setText("C");
        Bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclearActionPerformed(evt);
            }
        });

        Bsave.setText("GUARDAR");
        Bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsaveActionPerformed(evt);
            }
        });

        panel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        panel1.setToolTipText("");
        panel1.setOpaque(true);

        imaginario.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        imaginario.setToolTipText("");
        imaginario.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CALCULADORA ARITMETICA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imaginario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BNuno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bdos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BNtres, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BNcuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BNcinco, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BNseis, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BNsiete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Braizn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Belevacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BNocho, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BNcero, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Braiz, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BNnueve, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Bmen, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(Binverso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bresta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Bmultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addComponent(Bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Bsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bdivision, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bfactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bsave)
                                .addContainerGap(111, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imaginario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BNuno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bdos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BNtres, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BNcuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BNcinco, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BNseis, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bresta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BNocho, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BNcero, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Braiz, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BNnueve, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bmultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Bmen, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bdivision, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Binverso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bfactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BNsiete, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Braizn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Belevacion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bigual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(Bclear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Bsave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void BNceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNceroActionPerformed
        this.panel.setText(this.panel.getText()+"0");
        
    }//GEN-LAST:event_BNceroActionPerformed

    private void BNunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNunoActionPerformed
         this.panel.setText(this.panel.getText()+"1");
    }//GEN-LAST:event_BNunoActionPerformed

    private void BdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdosActionPerformed
         this.panel.setText(this.panel.getText()+"2");
    }//GEN-LAST:event_BdosActionPerformed

    private void BNtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNtresActionPerformed
         this.panel.setText(this.panel.getText()+"3");
    }//GEN-LAST:event_BNtresActionPerformed

    private void BNcuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNcuatroActionPerformed
         this.panel.setText(this.panel.getText()+"4");
    }//GEN-LAST:event_BNcuatroActionPerformed

    private void BNcincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNcincoActionPerformed
         this.panel.setText(this.panel.getText()+"5");
    }//GEN-LAST:event_BNcincoActionPerformed


    private void BNseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNseisActionPerformed
         this.panel.setText(this.panel.getText()+"6");
    }//GEN-LAST:event_BNseisActionPerformed

    private void BNsieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNsieteActionPerformed
         this.panel.setText(this.panel.getText()+"7");
    }//GEN-LAST:event_BNsieteActionPerformed

    private void BNochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNochoActionPerformed
         this.panel.setText(this.panel.getText()+"8");
    }//GEN-LAST:event_BNochoActionPerformed


    private void BNnueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNnueveActionPerformed
         this.panel.setText(this.panel.getText()+"9");
    }//GEN-LAST:event_BNnueveActionPerformed

    private void BmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmenActionPerformed

        this.panel1.setText("");
        this.snumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
        String PorMenos=String.valueOf(-1*(this.snumero));//CONVIERTE A MENOS EN EL LABEL
        this.panel.setText(PorMenos);
    }//GEN-LAST:event_BmenActionPerformed
    
    private void BsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsumaActionPerformed
         this.pnumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
         this.operacion="+";//QUE OPERACION ES 
         this.panel.setText("");//LIMPIAR LA PANTALLA
         this.panel1.setText("+");
    }//GEN-LAST:event_BsumaActionPerformed

    private void BrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrestaActionPerformed
        this.pnumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
        this.operacion="-";//QUE OPERACION ES 
        this.panel.setText("");//LIMPIAR LA PANTALLA
        this.panel1.setText("-");
    }//GEN-LAST:event_BrestaActionPerformed

    private void BmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmultiplicacionActionPerformed
        this.pnumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
        this.operacion="*";//QUE OPERACION ES 
        this.panel.setText("");//LIMPIAR LA PANTALLA
        this.panel1.setText("*");
    }//GEN-LAST:event_BmultiplicacionActionPerformed

    
    private void BdivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdivisionActionPerformed
        this.pnumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
        this.operacion="/";//QUE OPERACION ES 
        this.panel.setText("");//LIMPIAR LA PANTALLAs
        this.panel1.setText("/");
    }//GEN-LAST:event_BdivisionActionPerformed

    private void BfactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfactorialActionPerformed
        this.snumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
        this.operacion="!";
        this.panel1.setText("!");
    }//GEN-LAST:event_BfactorialActionPerformed

    private void BelevacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BelevacionActionPerformed
        this.pnumero=Double.parseDouble(this.panel.getText());
        this.operacion="^";
        this.panel.setText("");//LIMPIAR LA PANTALLAs
        this.panel1.setText("^");
    }//GEN-LAST:event_BelevacionActionPerformed

    private void BinversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinversoActionPerformed
        NOSE ns= new NOSE(); 
        this.panel1.setText("");
        this.snumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
        String PorMenos=ns.decimales(1/(this.snumero));//CONVIERTE A MENOS EN EL LABEL
        this.panel.setText(PorMenos);
        
    }//GEN-LAST:event_BinversoActionPerformed

     private void BraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BraizActionPerformed
        this.snumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
        this.operacion="r";
        this.panel1.setText("r");
    }//GEN-LAST:event_BraizActionPerformed

    private void BraiznActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BraiznActionPerformed
        this.pnumero=Double.parseDouble(this.panel.getText());//CONVIERTE EL TEXTO DEL LABEL A UN NUMERO
        this.operacion="rn";//QUE OPERACION ES 
        this.panel.setText("");//LIMPIAR LA PANTALLAs
        this.panel1.setText("rn");
    }//GEN-LAST:event_BraiznActionPerformed

    private int identificador=0;
    static String opera="";
  
    private void BigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BigualActionPerformed
        NOSE ns= new NOSE();
        this.snumero=Double.parseDouble(this.panel.getText());//String a double
        this.panel1.setText("");
        //JCalculadora jc= new JCalculadora(); 
        
        if("+".equals(operacion)){//CONDICION PARA VER QUE OPRACION ES
            this.panel.setText(ns.decimales(this.pnumero+this.snumero));//CONVERTIR DE DOUBLE A STRING
            opera="suma";
        }else if("-".equals(operacion)){
            this.panel.setText(ns.decimales(this.pnumero-this.snumero));
            opera="resta";
        }else if("*".equals(operacion)){
            this.panel.setText(ns.decimales(this.pnumero*this.snumero));
            opera="multiplicacion";
        }else if("/".equals(operacion)){
            opera="division";
            if(this.snumero==0){
                this.panel.setText("0");
                JOptionPane.showMessageDialog(null, "INFINITO");
            }else{
                this.panel.setText(ns.decimales(this.pnumero/this.snumero));
            }
        }else if("!".equals(operacion)){
            opera="factorial";
           String fact=ns.decimales(ns.factorial(this.snumero));//MIRO EL NUMERO LO PASO POR EL OPREADOR LUEGO LO CONVIERTE A 2 DECIMALES APROX Y DE ULTIMO A UN STRING Y LO IMPRIMO
           this.panel.setText(fact);
        }else if("^".equals(operacion)){
            opera="elevacion";
            String elevado=ns.decimales(ns.elevacion(this.pnumero,this.snumero));
            this.panel.setText(elevado);
        }else if("r".equals(operacion)){
            opera="raiz";
            if(this.snumero<0){
                String raiz=ns.decimales(ns.raizn(-1*this.snumero,2));
                this.panel.setText(raiz);
                this.imaginario.setText("i");
            }else{
                String raiz=ns.decimales(ns.raizn(this.snumero,2));
                this.panel.setText(raiz);
            }
            
        }else if("rn".equals(operacion)){
            opera="raiz";
            if(this.snumero<0){
                String raizn=ns.decimales(ns.raizn(-1*this.pnumero,this.snumero));
                this.panel.setText(raizn);
                this.imaginario.setText("i");
            }else{
                String raizn=ns.decimales(ns.raizn(this.pnumero,this.snumero));
                this.panel.setText(raizn);
            }
                
        }
       // ParaAlmacen pa= new ParaAlmacen();
        Calendar fecha = new GregorianCalendar();
        /**//**/
        String resultado=this.panel.getText();
        //OPERACION
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int mes = fecha.get(Calendar.MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        //IDENTIFICADOR
        if (identificador < datos.length) {
            if (datos[identificador] == null) {
                datos[identificador] = new ParaAlmacen(resultado, opera, dia, mes, hora, minuto,1,0);
                identificador++;
            } else {
                for (int z = identificador; z < datos.length; z++) {//4 TAMÑAO ACTUAL
                    if (datos[z] == null) {
                        datos[z] = new ParaAlmacen(resultado, opera, dia, mes, hora, minuto,1,0);
                        //identificador = z;
                        break;
                    } else {
                        
                    }
                }

            }
        }else{
            for(int z=1;z<datos.length;z++){
                datos[z-1]=datos[z];
            }datos[datos.length-1]=new ParaAlmacen(resultado,opera,dia,mes,hora,minuto,1,0);
        }
            
        
    }//GEN-LAST:event_BigualActionPerformed
    
    private void BclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclearActionPerformed
         this.panel.setText("");
    }//GEN-LAST:event_BclearActionPerformed

    private int contador=temp.Reg_FAV();
    private int CA=temp.REG_CA();
    private void BsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsaveActionPerformed
        
        Calendar fecha = new GregorianCalendar();
        /**//**/
        String resultado=this.panel.getText();
        //OPERACION
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int mes = fecha.get(Calendar.MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        //IDENTIFICADOR
        CA++;
        temp.IN_CA(CA);
        System.out.println(temp.REG_CA());
        
        if(contador<fav.length){
        if(fav[contador]==null){
            fav[contador]=new ParaAlmacen(resultado,opera,dia,mes,hora,minuto,1,temp.REG_CA());
            contador++;
            System.out.println(contador);
        }else{
            for(int z=contador;z<fav.length;z++){//4 TAMÑAO ACTUAL
                if(fav[z]==null){
                    fav[z]=new ParaAlmacen(resultado,opera,dia,mes,hora,minuto,1,temp.REG_CA());
                    //contador=z;
                    System.out.println(contador);
                    break;
                }else{
                   contador=fav.length+10;
                }
            }
            
        }
        }else{
            for(int z=1;z<fav.length;z++){
                fav[z-1]=fav[z];
            }fav[fav.length-1]=new ParaAlmacen(resultado,opera,dia,mes,hora,minuto,1,temp.REG_CA());
        }
        if(contador==fav.length-1){
            temp.In_FAV(fav.length);
        }
       
//GEN-LAST:event_BsaveActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNcero;
    private javax.swing.JButton BNcinco;
    private javax.swing.JButton BNcuatro;
    private javax.swing.JButton BNnueve;
    private javax.swing.JButton BNocho;
    private javax.swing.JButton BNseis;
    private javax.swing.JButton BNsiete;
    private javax.swing.JButton BNtres;
    private javax.swing.JButton BNuno;
    private javax.swing.JButton Bclear;
    private javax.swing.JButton Bdivision;
    private javax.swing.JButton Bdos;
    private javax.swing.JButton Belevacion;
    private javax.swing.JButton Bfactorial;
    private javax.swing.JButton Bigual;
    private javax.swing.JButton Binverso;
    private javax.swing.JButton Bmen;
    private javax.swing.JButton Bmultiplicacion;
    private javax.swing.JButton Braiz;
    private javax.swing.JButton Braizn;
    private javax.swing.JButton Bresta;
    private javax.swing.JButton Bsave;
    private javax.swing.JButton Bsuma;
    private javax.swing.JLabel imaginario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel panel1;
    // End of variables declaration//GEN-END:variables
}
