package calculadora;

import static calculadora.JVistaPrincipal.datos;
import static calculadora.JVistaPrincipal.fav;
import java.awt.BasicStroke;
import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

public class JLArco extends javax.swing.JFrame {

    /**
     * Creates new form JLArco
     */
    public JLArco() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("LONGITUD DE ARCO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GradRad = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        Res = new javax.swing.JLabel();
        TAngulo = new javax.swing.JTextField();
        TRadio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bsave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        GradRad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grados", "Radianes" }));

        jButton2.setText("CALCULAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Res.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Res.setToolTipText("");
        Res.setOpaque(true);

        jLabel1.setText("ANGULO");

        jLabel2.setText("RADIO");

        Bsave.setText("GUARDAR");
        Bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(TAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Res, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(GradRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Bsave)))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GradRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Res, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bsave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int identificador=0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NOSE ns= new NOSE();
        double pi = 3.14159265358979323846;
        String GR=GradRad.getSelectedItem().toString();
        Double Dan=Double.parseDouble(TAngulo.getText());
        Double Drad=Double.parseDouble(TRadio.getText());
        
        
        Calendar fecha = new GregorianCalendar();
        /**//**/
        String resultado=this.Res.getText()+" "+GR;
        //OPERACION
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int mes = fecha.get(Calendar.MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        //IDENTIFICADOR
        if (identificador < datos.length) {
            if (datos[identificador] == null) {
                datos[identificador] = new ParaAlmacen(resultado, "L de arco", dia, mes, hora, minuto,1,0);
                identificador++;
            } else {
                for (int a = identificador; a < datos.length; a++) {//4 TAMÑAO ACTUAL
                    if (datos[a] == null) {
                        datos[a] = new ParaAlmacen(resultado, "L de arco", dia, mes, hora, minuto,1,0);
                        //identificador = a;
                        break;
                    } else {

                    }
                }

            }
        }else{
            for(int z=1;z<datos.length;z++){
                datos[z-1]=datos[z];
            }datos[datos.length-1]=new ParaAlmacen(resultado, "L de arco", dia, mes, hora, minuto,1,0);
        }
        
        
        
        
        
        
        
        //EMPIEZA LA GRAFICADORA
        XYSeries ALarco = new XYSeries("Grafica");XYSeries BLarco = new XYSeries("Angulo:" +Dan);//GRAFICAR LA PARTE DE ARRIBA Y ABAJO
        
        if(GR.equals("Radianes")){
            Res.setText(ns.decimales(Dan*Drad));//DA EL RESULTADO
            double d=Dan*(180/pi);
            
            //RADIANES
            for(int i=0;i<=d;i++)//CREA LOS PUNTOS PARA PLOTEARLOS
            {
                double cos=ns.CosSen(i*pi/180,0);
                double sen=ns.CosSen(i*pi/180, 1);
                double x=Drad*cos;
                double y=Drad*sen;
                if(i<=180){
                    ALarco.add(x,y);
                }else if(i>360){
                    break;
                }
                else{
                    BLarco.add(x,y);
                }
            }
            
        }else{
            double d=Dan*(pi/180);
            Res.setText(ns.decimales(d*Drad));//DA EL RESULTADO
            
            //GRADOS
            for(int i=0;i<=Dan;i++)//CREA LOS PUNTOS PARA PLOTEARLOS
            {
                double cos=ns.CosSen(i*pi/180,0);
                double sen=ns.CosSen(i*pi/180, 1);
                double x=Drad*cos;
                double y=Drad*sen;
                if(i<=180){
                    ALarco.add(x,y);
                }else if(i>360){
                    break;
                }
                else{
                    BLarco.add(x,y);
                }
            }
        }
        
        //INGRESO PARA PLOTEAR LOS PUNTOS
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(ALarco);dataset.addSeries(BLarco);
        //NOMBRE DE LA GRAFICA, EN LOS EJES X y Y        
        JFreeChart xylineChart = ChartFactory.createScatterPlot( "Grafica","","",dataset);
        //
        XYPlot plot = xylineChart.getXYPlot();
        //EDITAR EL COLOR DE LAS GRAFICAS
        XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
        renderer.setSeriesPaint(0, Color.RED);
        renderer.setSeriesStroke(0, new BasicStroke(8f));
        renderer.setSeriesPaint(1, Color.RED);
        renderer.setSeriesStroke(1, new BasicStroke(8f));
        //
        plot.setRenderer(renderer);         
        ChartPanel panel = new ChartPanel(xylineChart);
        //CREA LA VENTANA PARA PLOTEAR LAS ELIPSES
        JFrame ventana = new JFrame("Grafica");
        ventana.setVisible(true);
        ventana.setSize(900, 600);
        //ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//CIERRA EL PANEL
        ventana.add(panel);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    JTemp temp=new JTemp();
    private int contador=temp.Reg_FAV();
    private int LA=temp.REG_LA();
    private void BsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsaveActionPerformed
        Calendar fecha = new GregorianCalendar();
        /**//**/
        String GR=GradRad.getSelectedItem().toString();
        String resultado=this.Res.getText()+" "+GR;
        //OPERACION
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int mes = fecha.get(Calendar.MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        //IDENTIFICADOR
        LA++;
        temp.IN_LA(LA);
        System.out.println(temp.REG_LA());
        
        if(contador<fav.length){
            if(fav[contador]==null){
                fav[contador]=new ParaAlmacen(resultado, "L de arco", dia, mes, hora, minuto,1,temp.REG_LA());
                contador++;
                System.out.println(contador);
            }else{
                for(int z=contador;z<fav.length;z++){//4 TAMÑAO ACTUAL
                    if(fav[z]==null){
                        fav[z]=new ParaAlmacen(resultado, "L de arco", dia, mes, hora, minuto,1,temp.REG_LA());
                        //contador=z;
                        System.out.println(contador);
                        break;
                    }else{
                        contador=fav.length+10;
                    }
                }

            }
        }else{
            for(int z=1;z<fav.length;z++){
                fav[z-1]=fav[z];
            }fav[fav.length-1]=new ParaAlmacen(resultado, "L de arco", dia, mes, hora, minuto,1,temp.REG_LA());
        }System.out.println(contador);

        if(contador==fav.length-1){
            temp.In_FAV(fav.length);
        }

    }//GEN-LAST:event_BsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLArco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLArco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLArco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLArco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLArco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsave;
    private javax.swing.JComboBox<String> GradRad;
    private javax.swing.JLabel Res;
    private javax.swing.JTextField TAngulo;
    private javax.swing.JTextField TRadio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
