/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Rectangle;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class JMatUno extends javax.swing.JFrame {

    JTemp temp = new JTemp();//ARREGLO DEL TAMAÑO DEL NUMERO
    JPanel jpanel = (JPanel) this.getContentPane();
    public JTextField[] text = new JTextField[temp.Reg_XU() * temp.Reg_YU()];    //Declaración del array de cajas de texto
    public double[][] matriz = new double[temp.Reg_YU()][temp.Reg_XU()];
    double[][] matriz2 = new double[temp.Reg_YD()][temp.Reg_XD()];
    public String[] text2= new String[temp.Reg_XD()*temp.Reg_YD()];
    
    //Border border = BorderFactory.createLineBorder(Color.black, 1);
    public JMatUno() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("MATRIZ 1");
        setResizable(false);
        
        int d = 0;//PARA BAJAR UNA CASILLA EN Y
        int id = 0;//ID DE LA CAJA PARA QUE SEA DIFERENTE
        for (int a = 0; a < temp.Reg_YU(); a++) {
            for (int i = 0 + id; i < temp.Reg_XU() + id; i++) {//CILCO PAR IMPRIMIR LA
                text[i] = new JTextField();    //LLAMOS EL ARRAY A LA CAJA DE TEXTO
                text[i].setBounds(new Rectangle((i + 1 - id) * (35 + 40)/*POSICOIN X*/, 110 + d/*POSICOIN Y*/, 35, 20));
                jpanel.add(text[i], null);
            }

            id = id + temp.Reg_XU();
            d = d + 30;
        }
        UNO.setText("PRIMERA MATRIZ XY "+temp.Reg_XU()+" X "+temp.Reg_YU());
        DOS.setText("SEGUNDA MATRIZ XY "+temp.Reg_XD()+" X "+temp.Reg_YD());
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        sup = new javax.swing.JTextField();
        DOS = new javax.swing.JLabel();
        UNO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setText("OPERACIONES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sup.setText("MATRIZ NUMERO 2");

        DOS.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        DOS.setOpaque(true);

        UNO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UNO.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(UNO, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(DOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sup, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(362, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int kk = 0;//pasa a una matriz
        String cuadro = sup.getText();

        kk=0;
        for (int a = 0; a < temp.Reg_YU(); a++) {//PASA LOS TEXFIELD A UNA MATRIZ
            for (int b = 0; b < temp.Reg_XU(); b++) {
                JTextField texto = text[kk];//toma el texto de la matriz
                double mat = Double.parseDouble(texto.getText());
                matriz[a][b] = mat;
                kk++;
            }
        }
        ///CONVERTIR A NUMERO

        String unir = "0";
        String cero = "0";
        int id=0;
        char[] aCaracteres = cuadro.toCharArray();
        for (int a = 0; a < aCaracteres.length; a++) {

            if (aCaracteres[a] == ',') {//SI ES COMA GUARDA LOS NUMEROS
                text2[id]=cero;
                id++;
                cero = "0";
                unir = "0";
                continue;

            } else {
                unir = String.valueOf(aCaracteres[a]);
                cero = cero + unir;//CARACTER+CARACTER SIGUIENTE
                if(a==aCaracteres.length-1){//SI ES LA ULTIMA POSICION TOMA EL NUMERO
                    text2[id]=cero;
                }
            }

        }

        for(int a=0;a<temp.Reg_XD()*temp.Reg_YD();a++){
            if(text2[a]==null){
                text2[a]="0";
            }else{
                continue;
            }
            //INCIALIZARLA EN CERO
        }

        kk=0;
        for (int a = 0; a < temp.Reg_YD(); a++) {//PASA LOS TEXFIELD A UNA MATRIZ
            for (int b = 0; b < temp.Reg_XD(); b++) {
                matriz2[a][b] = Double.parseDouble(text2[kk]);
                kk++;
            }
        }

        temp.In_Ma(matriz);
        temp.In_Mb(matriz2);

        /*for (int a = 0; a < temp.Reg_YU(); a++) {
            for (int b = 0; b < temp.Reg_XU(); b++) {
                System.out.print(matriz[a][b]+"|");
            }
            System.out.println();
        }
        for (int a = 0; a < temp.Reg_YD(); a++) {
            for (int b = 0; b < temp.Reg_XD(); b++) {
                System.out.print(matriz2[a][b]+"|");
            }
            System.out.println();
        }*/
        new OPERACIONES().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMatUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMatUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMatUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMatUno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMatUno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOS;
    private javax.swing.JLabel UNO;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField sup;
    // End of variables declaration//GEN-END:variables
}
